
#====================================================
#A)Configuration
#====================================================
#Packages
cat("\014")  
cat("========================================================================================\n")
cat("\tGenetic algorithm for feature selection \n")
cat("========================================================================================\n")
cat("----------------------------------------------------------------------------------------\n")
cat("\t\tA)\tInitial configuration\n")
cat("----------------------------------------------------------------------------------------\n")
cat("\t\t\t- Loading packages...\n")
if (!require("clusteval")) install.packages("clusteval")
library("clusteval")
if (!require("parallel")) install.packages("parallel")
library("parallel")
if (!require("flexclust")) install.packages("flexclust")
library("flexclust")
if (!require("yaml")) install.packages("yaml")
library("yaml")
if (!require("cluster")) install.packages("cluster")
library("cluster")
if (!require("caret")) install.packages("caret")
library("caret")
if (!require("mlbench")) install.packages("mlbench")
library("mlbench")
if (!require("snn")) install.packages("snn")
library("snn")
if (!require("proxy")) install.packages("proxy")
library("proxy")
if (!require("protoclass")) install.packages("protoclass")
library("protoclass")
if (!require("randomForest")) install.packages("randomForest")
library("randomForest")
if (!require("hyperSpec")) install.packages("hyperSpec")
library("hyperSpec")
if (!require("FSelector")) install.packages("FSelector")
library("FSelector")
if (!require("amap")) install.packages("amap")
library("amap")
if (!require("unbalanced")) install.packages("unbalanced")
library("unbalanced")

